# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            NataleVinto.IT
tagline:          'kubernetes,openshift,opensource,blues'
description:      '*Engineer. Linux. Containers. Kubernetes. OOP and Functions. <a href="https://twitter.com/natalevinto" target="_blank">@natalevinto</a>'
url:              http://natalevinto.IT/
baseurl:          /

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

author:
  name:           'natalevinto'
  url:            https://twitter.com/natalevinto

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/blues-man/natalevinto.github.io

accounts:
  github:         https://github.com/blues-man
  linkedin:       https://linkedin.com/in/natalevinto
  speakerhub:     https://speakerhub.com/speaker/natale-vinto
